gantt
    title Plan de Trabajo del Sistema de Gestión Hospitalaria
    dateFormat  YYYY-MM-DD

    section Fundamentación y Aprendizaje
    Tareas y Aprendizaje básico :a1, 2023-10-02, 28d
    
    section Diseño y Prototipado
    Recopilación y Validación de Requisitos :a2, after a1, 42d
    Mock-ups de UI/UX : after a2, 42d
    
    section Fase de Desarrollo 1 (Backend)
    Configuración de Base de Datos y Autenticación :a3, after a2, 56d
    Lógica de Negocio : after a3, 56d
    Sistema de Advertencias y Notificaciones : after a3, 56d
    
    section Fase de Desarrollo 2 (Frontend)
    Diseño de UI :a4, after a3, 56d
    Integración con la Lógica de Backend : after a4, 56d
    
    section Integración y Pruebas
    Integración de Componentes :a5, after a4, 28d
    Pruebas Completas : after a5, 28d
    
    section Despliegue y Retroalimentación
    Preparación para el Despliegue :a6, after a5, 14d
    Retroalimentación Inicial : after a6, 14d

    section Iteración y Aprendizaje Adicional
    Retroalimentación y Mejora Iterativa :a7, after a6, 84d
    Aprendizaje Continuo : ongoing, after a6, 84d


graph TD;
    A[Inicio: Hoy] --> B[¿Se rió de mi último chiste?]
    B -->|Sí| C[¿Recordé nuestro aniversario?]
    B -->|No| Z[Agregar 1 año más]
    C -->|Sí| D[¿Hice mis tareas de la casa esta semana?]
    C -->|No| Z
    D -->|Sí| E[¿Su programa favorito se emite esta noche?]
    D -->|No| Z
    E -->|Sí| F[Quizás después del último episodio de la temporada]
    E -->|No| G[¿Cuán brillante es el anillo?]
    G -->|Muy brillante| H[Proponer mañana]
    G -->|Un poco brillante| I[Esperar una fecha especial]
    G -->|No es brillante| Z
