gantt
    title Plan de Trabajo del Sistema de Gestión Hospitalaria
    dateFormat  YYYY-MM-DD

    section Fundamentación y Aprendizaje
    Tareas y Aprendizaje básico :a1, 2023-10-02, 28d
    
    section Diseño y Prototipado
    Recopilación y Validación de Requisitos :a2, after a1, 42d
    Mock-ups de UI/UX : after a2, 42d
    
    section Fase de Desarrollo 1 (Backend)
    Configuración de Base de Datos y Autenticación :a3, after a2, 56d
    Lógica de Negocio : after a3, 56d
    Sistema de Advertencias y Notificaciones : after a3, 56d
    
    section Fase de Desarrollo 2 (Frontend)
    Diseño de UI :a4, after a3, 56d
    Integración con la Lógica de Backend : after a4, 56d
    
    section Integración y Pruebas
    Integración de Componentes :a5, after a4, 28d
    Pruebas Completas : after a5, 28d
    
    section Despliegue y Retroalimentación
    Preparación para el Despliegue :a6, after a5, 14d
    Retroalimentación Inicial : after a6, 14d

    section Iteración y Aprendizaje Adicional
    Retroalimentación y Mejora Iterativa :a7, after a6, 84d
    Aprendizaje Continuo : ongoing, after a6, 84d
